config/routes.rb
Media::Application.routes.draw do
 
  root 'media#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users

  get '/unwatched', to: 'media#unwatched', as: :unwatched
  get '/view', to: 'media#view', as: :view
  get "media/add", as: :add
  post 'media/select'
  post 'media/new'
  resources :media

end

app/models/medium.rb
require 'textacular/searchable'

class Medium < ActiveRecord::Base
  

  #serialize :genre, Array
  #serialize :cast, Array    

  #before_validation :update_genre
  #before_validation :update_cast
  
  validates :title, presence: true, uniqueness: { case_sensitive: false }


  #validates :own, presence: true
  #validates :watched, presence: true

  scope :watched, -> watched { where(watched: watched) }
  scope :own, -> own { where(own: own) }
  
  extend Searchable(:title, :genre, :director, :cast)

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |medium|
        csv << medium.attributes.values_at(*column_names)
      end
    end
  end 

  def self.text_search(query)
    if query.present?
      search(query)
    else
      find(:all)
    end
  end


  #def update_genre
   # if genre_changed?
   # self.genre = self.genre.split(',').collect(&:strip)
   # end
  #end
  
  #def update_cast
   # if cast_changed?
    #self.cast = self.cast.split(',').collect(&:strip)
   # end
  #end

 end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_uniqueness_of :username

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
    	redirect_to login_url, alert: "Not authorized" if current_user.nil?
    end


end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  include RottenTomatoes
  helper_method :sort_column, :sort_direction
  before_filter :authorize, only: [:edit, :update, :create, :new, :destroy]

  
  before_action :set_medium, only: [:show, :edit, :update, :destroy]


  # GET /media
  # GET /media.json
  def index
    @media = Medium.all
    respond_to do |format|
      format.html
      format.csv { send_data @media.to_csv }
    end
  end

  # GET /media/1
  # GET /media/1.json
  def show
  end

  def add
    Rotten.api_key = "g5dzadjs35ee5aagrvm84ezy" 
    @medium = Medium.new
  end
  
  def select
    @medium = Medium.new(medium_params)
    @selections = RottenMovie.find(:title => @medium.title).collect {|s| [s.title, s.id.to_i] }
    if @selections.blank?
      redirect_to(:action => 'new', :title => @medium.title) 
    end 
  end
     
  # GET /media/new -changed (medium_params
  def new
    if params[:medium].present?
      @medium = Medium.new(medium_params)
      @rotten = RottenMovie.find(:id => @medium.rotten_id)
    else @medium = Medium.new
      @medium.title = params['title']
    end
  end

  # GET /media/1/edit
  def edit
  end

  # POST /media
  # POST /media.json
  def create
    @medium = Medium.new(medium_params)
    
    respond_to do |format|
      if @medium.save
        format.html { redirect_to add_path, notice: 'Medium was successfully created.' }
        format.json { render action: 'add', status: :created, location: @medium }
      else
        format.html { render action: 'add' }
        format.html { render action: 'new' }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media/1
  # PATCH/PUT /media/1.json
  def update
    respond_to do |format|
      if @medium.update(medium_params)
        format.html { redirect_to @medium, notice: 'Medium was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.json
  def destroy
    @medium.destroy
    respond_to do |format|
      format.html { redirect_to media_url }
      format.json { head :no_content }
    end
  end
  
  def queue
    #netflix style list of unowned and unwatched movies
    @media = Medium.watched(false).own(false)
  end

  def unwatched
    #list of unwatched owned movies
    @media = Medium.paginate(:page => params[:page], :per_page => 25).watched(false).own(true).order(sort_column + " " + sort_direction, title: :asc).text_search(params[:query])
  end

  def view
    # Look at the all owned in pretty format
    @media = Medium.paginate(:page => params[:page], :per_page => 25).own(true).order(sort_column + " " + sort_direction, title: :asc).text_search(params[:query])
  end
  
  def watch
    # watch the media
  end
  
  def list
    # create a CRUD list and then use the index for a pretty view
    @media = Medium.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medium
     @medium = Medium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medium_params
      params.require(:medium).permit(:title, :runtime, :genre, :platform, :director, :cast, :release_date, :critic_rating, :audience_rating, :foreign, :summary, :trailer_link, :movie_link, :rotten_id, :poster_link, :watched, :hassan_rating, :own)
    end


    def sort_column
      Medium.column_names.include?(params[:sort]) ? params[:sort]  : "critic_rating"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out" 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  private

  def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def sortable (column, title = nil)
		title ||= column.titleize
		css_class = column == sort_column ? "direction #{sort_direction}" : nil
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, {:sort => column, :direction => direction, :query => params[:query]}, {:class => css_class}
	end

end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Media" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          
          <%= link_to "Database", media_path, :class => 'brand' %>
          <%= link_to "Download", media_path(format: "csv"), :class => 'brand' %>
          <%= link_to "Add", add_path, :class => 'brand' %>
          <%= link_to "Collection", view_path, :class => 'brand' %>
          <%= link_to "Unwatched", unwatched_path, :class => 'brand' %>
          <div id="authorize">
          <% if current_user %>
            <%= link_to "Log Out", logout_path, :class => 'btn btn-danger' %>
          <% else %>
            <%= link_to "Admin Log In", login_path, :class => 'btn btn-info' %>
          <% end %>  
          </div>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%#= link_to "Link1", "/path1"  %></li>
              <li><%#= link_to "Link2", "/path2"  %></li>
              <li><%#= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <br /><p>&copy; Beachmaster Inc. 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/media/_form.html.erb
<%= form_for @medium, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, {:value => @medium.title}%>
    </div>
  </div>
  <div class="control-group">

    <%= f.label :watched, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :watched, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :own, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :own, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">

    <%= f.label :runtime, "Runtime in minutes", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :runtime, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :genre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :genre, {:value => ""} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :platform, :class => 'control-label' %>
    <div class="controls">
      <%= f.radio_button :platform, "movie", :class => 'text_field radio inline' %>
	  <%= label_tag :platform_movie, "Movie", :class => 'radio inline' %>
	  <%= f.radio_button :platform, "televison", :class => 'text_field radio inline' %>
	  <%= label_tag :platform_television, "Television", :class => 'radio inline'%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :director, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :director, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cast, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cast, {:value => ""} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :release_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_field :release_date, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :critic_rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :critic_rating, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :audience_rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :audience_rating, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :foreign, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :foreign, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :summary, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :summary, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :trailer_link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :trailer_link, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :movie_link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :movie_link, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :poster_link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :poster_link, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :hassan_rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:hassan_rating, [[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]], :include_blank => true, :class => 'text_field') %>
    </div>
  </div>


	  

  <div class="form-actions">

    <%= f.submit "Update Media", :class => 'btn btn-primary' %>

    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                media_path, :class => 'btn' %>
  </div>
<% end %>

app/views/media/_form_rotten.html.erb
<%= form_for @medium, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, {:value => @rotten.title} %>
    </div>
  </div>
  <div class="control-group">

    <%= f.label :watched, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :watched, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :own, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :own, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">

    <%= f.label :runtime, "Runtime in minutes", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :runtime, {:value => @rotten.runtime} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :genre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :genre, {:value => @rotten.genres.to_s[1..-2].gsub(/["]/, "")} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :platform, :class => 'control-label' %>
    <div class="controls">
      <%= f.radio_button :platform, "movie", :class => 'text_field radio inline' %>
	  <%= label_tag :platform_movie, "Movie", :class => 'radio inline' %>
	  <%= f.radio_button :platform, "televison", :class => 'text_field radio inline' %>
	  <%= label_tag :platform_television, "Television", :class => 'radio inline'%>
    </div>
  </div>
  <div class="control-group">

    <% if @rotten.abridged_directors.nil? %>
      <%= f.label :director, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :director, :class => 'text_field' %>
      </div>
    <% else %>
      <%= f.label :director, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :director, {:value => @rotten.abridged_directors.collect(&:name).to_s[1..-2].gsub(/["]/, "")} %>
      </div>
    <% end %>

  </div>
  <div class="control-group">
    <%= f.label :cast, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cast, {:value => @rotten.abridged_cast.collect(&:name).to_s[1..-2].gsub(/["]/, "")} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :release_date, :class => 'control-label' %>
    <div class="controls">
	<%= f.date_field :release_date, {:value => @rotten.release_dates.theater} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :critic_rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :critic_rating, {:value => @rotten.ratings.critics_score} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :audience_rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :audience_rating, {:value => @rotten.ratings.audience_score} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :foreign, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :foreign, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :summary, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :summary, {:value => @rotten.synopsis} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :trailer_link, :class => 'control-label' %>
    <div class="controls">

      <%= f.text_field :trailer_link, {:value => @rotten.links.clips} %>

    </div>
  </div>
  <div class="control-group">
    <%= f.label :movie_link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :movie_link, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :poster_link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :poster_link, {:value => @rotten.posters.original} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :hassan_rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:hassan_rating, [[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]], :include_blank => true, :class => 'text_field') %>
    </div>
  </div>

  <%= f.hidden_field :rotten_id, :value => @rotten.id %>

  <div class="form-actions">
    <%= f.submit "Add Media", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                media_path, :class => 'btn' %>
  </div>
<% end %>

app/views/media/edit.html.erb
<%- model_class = Medium -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/media/index.html.erb
<%- model_class = Medium -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <p>
    Download:
    <%= link_to "CSV", media_path(format: "csv") %>
  </p>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:runtime) %></th>
      <th><%= model_class.human_attribute_name(:genre) %></th>
      <th><%= model_class.human_attribute_name(:platform) %></th>
      <th><%= model_class.human_attribute_name(:director) %></th>
      <th><%= model_class.human_attribute_name(:cast) %></th>
      <th><%= model_class.human_attribute_name(:release_date) %></th>
      <th><%= model_class.human_attribute_name(:critic_rating) %></th>
      <th><%= model_class.human_attribute_name(:audience_rating) %></th>
      <th><%= model_class.human_attribute_name(:foreign) %></th>
      <th><%= model_class.human_attribute_name(:watched) %></th>
      <th><%= model_class.human_attribute_name(:hassan_rating) %></th>
      <th><%= model_class.human_attribute_name(:own) %></th>
      <th><%= model_class.human_attribute_name(:summary) %></th>
      <th><%= model_class.human_attribute_name(:trailer_link) %></th>
      <th><%= model_class.human_attribute_name(:movie_link) %></th>
      <th><%= model_class.human_attribute_name(:poster_link) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @media.each do |medium| %>
      <tr>
        <td><%= link_to medium.id, medium_path(medium) %></td>
        <td><%= medium.title %></td>
        <td><%= medium.runtime %> Minutes</td>
        <td>
          <% if medium.genre.blank? %> no
          <% else %> yes
          <% end %>
        </td>
        <td><%= medium.platform %></td>
        <td><%= medium.director %></td>
        <td>
          <% if medium.cast.blank? %> no
          <% else %> yes
          <% end %>
        </td>
        <td><%= medium.release_date %></td>
        <td><%= medium.critic_rating %></td>
        <td><%= medium.audience_rating %></td>
        <td><%= medium.foreign %></td>
        <td><%= medium.watched %></td>
        <td><%= medium.hassan_rating %></td>
        <td><%= medium.own %></td>
        <td>
          <% if medium.summary.blank? %> no
          <% else %> yes
          <% end %>
        </td>
        <td><%= medium.trailer_link %></td>
        <td><%= medium.movie_link %></td>
        <td><%= medium.poster_link %></td>
        <td><%=l medium.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_medium_path(medium), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      medium_path(medium),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to("new", {:action => 'add'}, :class => 'btn btn-primary') %>

app/views/media/unwatched.html.erb
<%- model_class = Medium -%>

<%= form_tag(unwatched_path, method: "get", :class => "form-inline") do %>
  <p>
    <%= text_field_tag :query, params[:query], :class => 'text-field' %>
    <%= submit_tag "Search Unwatched", :name => nil, :class => 'btn btn-primary' %>
    <%= link_to "Clear", unwatched_path, :class => 'btn' %>
  </p>
<% end %>  


<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable "title" %></th>
      <th>Poster</th>
      <th><%= sortable "runtime" %></th>
      <th><%= model_class.human_attribute_name(:genre) %></th>
      <th><%= model_class.human_attribute_name(:director) %></th>
      <th><%= model_class.human_attribute_name(:cast) %></th>
      <th><%= sortable "release_date" %></th>
      <th><%= sortable "critic_rating" %></th>
      <th><%= sortable "audience_rating" %></th>
      <th><%= model_class.human_attribute_name(:foreign) %></th>
      <th><%= model_class.human_attribute_name(:summary) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @media.each do |medium| %>
      <tr>
        <td><%= link_to medium.title, medium_path(medium) %></td>
        <td><img src="<%= medium.poster_link %>" class="table_poster"></td>
        <td><%= medium.runtime%> Minutes</td>
        <td><%= medium.genre %></td>
        <td><%= medium.director %></td>
        <td><%= medium.cast %></td>
        <td><%= medium.release_date %></td>
        <td><%= medium.critic_rating %></td>
        <td><%= medium.audience_rating %></td>
        <td><%= medium.foreign %></td>
        <td>
          <% if medium.summary.blank? %> no
          <% else %> yes
          <% end %>
        </td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_medium_path(medium), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      medium_path(medium),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= will_paginate @media %>

app/views/media/view.html.erb
<%- model_class = Medium -%>

<%= form_tag(view_path, method: "get", :class => "form-inline") do %>
  <p>
    <%= text_field_tag :query, params[:query], :class => 'text-field' %>
    <%= submit_tag "Search Collection", :name => nil, :class => 'btn btn-primary' %>
    <%= link_to "Clear", view_path, :class => 'btn' %>
  </p>
<% end %>  


<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable "title" %></th>
      <th>Poster</th>
      <th><%= sortable "runtime" %></th>
      <th><%= model_class.human_attribute_name(:genre) %></th>
      <th><%= model_class.human_attribute_name(:director) %></th>
      <th><%= model_class.human_attribute_name(:cast) %></th>
      <th><%= sortable "release_date" %></th>
      <th><%= sortable "critic_rating" %></th>
      <th><%= sortable "audience_rating" %></th>
      <th><%= sortable "hassan_rating" %></th>
      <th><%= model_class.human_attribute_name(:foreign) %></th>
      <th><%= model_class.human_attribute_name(:summary) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @media.each do |medium| %>
      <tr>
        <td><%= link_to medium.title, medium_path(medium) %></td>
        <td><img src="<%= medium.poster_link %>" class="table_poster"></td>
        <td><%= medium.runtime%> Minutes</td>
        <td><%= medium.genre %></td>
        <td><%= medium.director %></td>
        <td><%= medium.cast %></td>
        <td><%= medium.release_date %></td>
        <td><%= medium.critic_rating %></td>
        <td><%= medium.audience_rating %></td>
        <td><%= medium.hassan_rating %></td>
        <td><%= medium.foreign %></td>
        <td>
          <% if medium.summary.blank? %> no
          <% else %> yes
          <% end %>
        </td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_medium_path(medium), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      medium_path(medium),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= will_paginate @media %>